name: "Slack Notify node edition"
description: "Send a notification to Slack directly from GitHub Actions without Docker."
author: "tainakanchu"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "bell"
  color: "yellow"
